export { default as Navbar } from './Navbar'
export { default as Products } from './Products'
export { default as Cart } from './Cart'
export { default as Checkout } from './CheckoutForm'
export { default as Footer } from './Footer'
export { default as Faq } from './Faq'
export { default as Categories } from './Categories'
export { default as About } from './About'
